### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by qbold** [AniketRajpoot/DeepMusicGeneration#1]
Hello! 
Great project!

I want to try to generate some samples, but I didnt find pretrained checkpoints here.

Could you publish it?

**Comment by AniketRajpoot** [comment]
@qbold, thank you so much for your feedback! 
I will upload all the checkpoints by this weekend, thank you!

**Comment by AniketRajpoot** [comment]
I have added very basic models, can you check ?

**Comment by qbold** [comment]
Thank you very much!

One more question - I need N_VOCAB that is computed on "final_list". Where I can find the needed value of N_VOCAB to run inference?

**Comment by AniketRajpoot** [comment]
Can you please tell me which code you are referring to ?
So I can tell you exactly, anyways I am uploading the notebook for the testing you can check there!! 
Thank you :)

**Comment by AniketRajpoot** [comment]
Here is the complete notebook containing everything expect training data code : https://github.com/AniketRajpoot/DeepMusicGeneration/blob/master/notebooks/Transformer_Genre_Evaluation.ipynb

![image](https://user-images.githubusercontent.com/52102674/197330091-8cee58be-9f96-4ac8-ba80-3171063883e6.png)

As you might notice there is no explicit N_VOCAB, you just need to initialize MusicVocab and it creates the vocabulary and manages it. Please try to refer it and hope this solves your problem. Otherwise please contact me again 😄 !

**Comment by qbold** [comment]
Yeah it works!
Thank you very much!!
One more question - there is a possibility to specify which instruments to generate?

**Comment by AniketRajpoot** [comment]
@qbold I think we included that feature but I don't think it works really well!

**Comment by AniketRajpoot** [comment]
I think I will close this issue now, as the initial problem is solved for the feature part @qbold I will contact you once I update everything up! 
Thanks :)
